/*
 * Copyright 2025 EMBL - European Bioinformatics Institute
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package uk.ac.ebi.embl.gff3tools.validation.provider;

import java.util.Objects;
import java.util.Optional;
import lombok.Getter;
import uk.ac.ebi.embl.api.entry.genomeassembly.AssemblyType;
import uk.ac.ebi.embl.gff3tools.utils.AssemblyTypeValidator;
import uk.ac.ebi.embl.gff3tools.utils.GapOptionsValidator;

/**
 * User-supplied analysis settings made available to fixes and validators via the
 * validation context.
 *
 * <p>All of these are external input: the {@link AnalysisType}, the minimum gap size, and the
 * optional {@code gap_type} / {@code linkage_evidence} stamped onto gap features generated by
 * {@code GapGenerationFix}. The minimum gap size must always be greater than zero.
 *
 * <p>The gap options are validated here rather than only at the CLI, because this constructor is
 * the single point every value passes through — a programmatic caller therefore cannot install an
 * invalid {@code gap_type} on the context. That matters because generated gap features are added
 * after the FEATURE-level rules have run, so {@code AssemblyGapValidation} never re-checks them.
 */
public final class AnalysisContext {

    @Getter
    private final AnalysisType analysisType;

    /*** Only available when supplied for {@link AnalysisType}.{@code SEQUENCE_ASSEMBLY} */
    @Getter
    private final Optional<AssemblyType> assemblyType;

    @Getter
    private final int minGapSize;

    /** Optional INSDC gap_type for generated gap features; {@code null} when not supplied. */
    @Getter
    private final String gapType;

    /** Optional INSDC linkage_evidence for generated gap features; {@code null} when not supplied. */
    @Getter
    private final String linkageEvidence;

    /**
     * @param analysisType the analysis type (must not be {@code null})
     * @param minGapSize   the minimum gap size (must be greater than zero)
     * @throws NullPointerException     if {@code analysisType} is {@code null}
     * @throws IllegalArgumentException if {@code minGapSize} is not greater than zero
     */
    public AnalysisContext(AnalysisType analysisType, int minGapSize) {
        this(analysisType, minGapSize, null, null, null);
    }

    /**
     * @param analysisType the analysis type (must not be {@code null})
     * @param minGapSize   the minimum gap size (must be greater than zero)
     * @throws NullPointerException     if {@code analysisType} is {@code null}
     * @throws IllegalArgumentException  if {@code minGapSize} is not greater than zero, or if the
     *                                 gap_type / linkage_evidence combination is not valid INSDC, or if if
     *                                       {@code assemblyType} is supplied for an analysis type other
     *                              than {@link AnalysisType#SEQUENCE_ASSEMBLY}, or if it does
     *                               not match a known assembly type
     */
    public AnalysisContext(AnalysisType analysisType, int minGapSize, String gapType, String linkageEvidence) {
        this(analysisType, minGapSize, gapType, linkageEvidence, null);
    }

    /**
     * @param analysisType    the analysis type (must not be {@code null})
     * @param minGapSize      the minimum gap size (must be greater than zero)
     * @param gapType         optional gap_type for generated gaps; blank is treated as not supplied
     * @param linkageEvidence optional linkage_evidence for generated gaps; blank is treated as not
     *                        supplied
     * @param assemblyType the raw assembly type, or {@code null}/blank when unavailable
     * @throws NullPointerException     if {@code analysisType} is {@code null}
     * @throws IllegalArgumentException if {@code minGapSize} is not greater than zero, or if the
     *                                  gap_type / linkage_evidence combination is not valid INSDC, or if
     *                                 {@code assemblyType} is supplied for an analysis type other
     *                               than {@link AnalysisType#SEQUENCE_ASSEMBLY}, or if it does
     *                                  not match a known assembly type
     */
    public AnalysisContext(
            AnalysisType analysisType, int minGapSize, String gapType, String linkageEvidence, String assemblyType) {
        this.analysisType = Objects.requireNonNull(analysisType, "analysisType must not be null");
        if (minGapSize <= 0) {
            throw new IllegalArgumentException("minGapSize must be greater than 0, but was " + minGapSize);
        }
        this.minGapSize = minGapSize;

        GapOptionsValidator.validate(gapType, linkageEvidence).ifPresent(message -> {
            throw new IllegalArgumentException(message);
        });

        // Stored in exactly the form GapOptionsValidator just checked: blank becomes null, and
        // gap_type is lower-cased, so a "Within Scaffold" that passed validation cannot be stamped
        // onto a feature as an INSDC value that does not exist.
        this.gapType = GapOptionsValidator.normaliseGapType(gapType);
        this.linkageEvidence = GapOptionsValidator.normaliseLinkageEvidence(linkageEvidence);
        this.assemblyType = AssemblyTypeValidator.parseAndValidate(analysisType, assemblyType);
    }
}
